{
 "title": "mi router",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "total download",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mi_router_wan_download" }
   ]
  },
  {
   "title": "total upload",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mi_router_wan_upload" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mi_router_cpu_usage * 100", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mi_router_memory_usage * 100", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    { "expr": "mi_router_wan_downspeed", "legendFormat": "Download" },
    { "expr": "mi_router_wan_upspeed", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "devices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mi_router_devices_total", "legendFormat": "total" },
    { "expr": "mi_router_devices_online", "legendFormat": "online" }
   ]
  },
  {
   "title": "devices download",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "mi_router_device_downspeed", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "devices upload",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "mi_router_device_upspeed", "legendFormat": "{{name}}" }
   ]
  }
 ]
}